//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageURL
    {
        public int ID { get; set; }
        public string LinkFormat { get; set; }
        public int LastPage { get; set; }
        public int TotalPage { get; set; }
    }
}
